### ISSUE TITLE
License

### ISSUE THREAD

**Issue by joelg236** [DaHoC/trainHOG#8]
I see this -> https://github.com/DaHoC/trainHOG/wiki/trainHOG-Tutorial#the-boring-legal-stuff

What license is the code here under?

**Comment by DaHoC** [comment]
Hi Joel,
I just decided that I put the code under the Apache 2.0 license.
Does this work for you? If not, just pass me a note, I am glad for anyone
using my code :-)

Kind regards,
Jan Hendriks
